- platform: ffmpeg
  input: !secret videocitofonostring
  name: Videocitofono
- platform: ffmpeg
  input: !secret cucinastring
  name: Cucina
- platform: ffmpeg
  input: !secret salonestring
  name: Salone
- platform: ffmpeg
  input: !secret lettostring
  name: Letto
- platform: ffmpeg
  input: !secret ingressostring
  name: Ingresso
- platform: ffmpeg
  input: !secret casettastring
  name: Casetta
- platform: ffmpeg
  input: !secret porticostring
  name: Portico

