homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret Location
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome

    
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  customize_glob: !include customize_glob.yaml

customizer:
  custom_ui: local
zone:
#  - name: !secret School
#    latitude: !secret Schoollatitude
#    longitude: !secret Schoollongitude
#    radius: 100
#    icon: mdi:work

#  - name: !secret WifeWork
#    latitude: !secret WifeWorklatitude
#    longitude: !secret WifeWorklongitude
#    radius: 250
#    icon: mdi:work

#  # This will override the default home zone
  - name: !secret Homelocation
    latitude:  !secret Homelocationlatitude
    longitude:  !secret Homelocationlongitude
    radius: 100
    icon: mdi:account-multiple
#

#lovelace:
#  mode: yaml

logger:
  default: info

# Show links to resources in log and frontend
#introduction:

# Enables configuration UI
config:

custom_updater:
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json?v=0
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json?v=0
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json?v=0
    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json?v=0
  component_urls:
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
    - https://raw.githubusercontent.com/danobot/entity-controller/master/tracker.json
    - https://raw.githubusercontent.com/zxdavb/evohome/master/custom_components.json
    - https://raw.githubusercontent.com/vinteo/hass-opensprinkler/master/custom_components.json

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://reinasserver.fritz.box:3218

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret api_password
#per ritornare a https://thereinas.it levare commenti sotto e port forward 443->8123
#  ssl_certificate: /etc/letsencrypt/live/thereinas.it/cert.pem
#  ssl_key: /etc/letsencrypt/live/thereinas.it/privkey.pem
  base_url: https://thereinas.it


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

system_health:

# Discover some devices automatically
discovery:
  ignore:
    - harmony
    - bose_soundtouch
    - songpal

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: it

# Cloud
cloud:
  alexa:
    filter:
      include_entities:
        - light.tavolo_salone
        - light.cucina
        - light.ingresso
        - light.divano
        - light.idro_CameraLetto
        - light.letto_CameraLetto
        - group.lucisalone
        - group.luciesterno
        - group.luciCameraLetto
        - group.luciale
        - group.lucicucina
      include_domains:
        - group
        - alert
        - automation 
        - cover
        - input_boolean
        - light
        - lock 
        - media_player 
        - scene
        - script
        - sensor
        - switch

    entity_config:
      light.tavolo_salone:
        name: Luce Tavolo Salone
        description: la luce del Tavolo del Salone
      light.cucina:
        name: Luce cucina
        description: la luce della cucina
      light.ingresso:
        name: Luce Ingresso
        description: la luce dell'ingresso
      light.divano:
        name: Luce Divano
        description: la luce del divano
      light.idro_CameraLetto:
        name: Luce Idro
        description: la luce dell'idro
      light.letto_CameraLetto:
        name: Luce Letto Giovanna Nicola
        description: la luce del letto Gio Nic
      group.lucisalone:
        name: luci salone
        description: luci salone
      group.luciale:
        name: luci ale
        description: luci ale
      group.lucicucina:
        name: luci cucina
        description: luci cucina

#  amzn1.ask.skill.31d2ff24-5617-448b-8cdc-1c666520a0b2:
#    action:
#      service: script.turn_on
#      entity_id: script.accendi_sky
#    speech:
#      type: plain
#      text: OK

mqtt:
  broker: ReinasServer.fritz.box
  port: 1883
  client_id: hass
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

xiaomi_aqara:
  discovery_retry: 15
  gateways:
    - mac: 34:CE:00:82:96:03
      key: !secret AquaraKey0
      host: XiaomiGateway0.fritz.box
    - mac: 7C:49:EB:19:03:79
      key: !secret AquaraKey1
      host: XiaomiGateway1.fritz.box

remote:
  - platform: harmony
    name: ReinasHarmony
    host: HarmonyHub.fritz.box

bmw_connected_drive:
  name:
    username: !secret BMWUSER
    password: !secret BMWPWD
    region: "rest_of_world"

#climate:
#  - platform: honeywell
#    username: !secret EvoHomeUser
#    password: !secret EvoHomePassword
#    scan_interval: 600

evohome:
  username: !secret EvoHomeUser
  password: !secret EvoHomePassword

ifttt:
  key: !secret IFTTKEY

recorder:
  db_url: mysql://hass:toorhass@localhost/hassdb

influxdb:
  host: Reinasserver.fritz.box
  port: 8086
  database: hass
  username: !secret influxuser
  password: !secret influxdbpassword

#/etc/udev/rules.d/99-usb-serial.rules 
#SUBSYSTEM=="tty", ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200", SYMLINK+="zwave"

zwave:
  usb_path: /dev/zwave

vacuum:
  - platform: xiaomi_miio
    host: rockrobo.fritz.box
    token: !secret VacuumKey

cover:
  platform: opengarage
  covers:
      garage:
        host:  opengarage.fritz.box
        device_key: !secret opengaragekey

#google_assistant:
#  project_id: homeassistantintegration-5af5b
#  client_id: !secret google_client_id
#  access_token:  !secret google_access_token
#  api_key: !secret google_api_key
#  exposed_domains:
#    - switch
#    - light
#    - group
#    - script

weblink:
  entities:
    - name: Router
      url: http://192.168.2.1/
      icon: mdi:router-wireless
    - name: Home Assistant
      url: https://www.home-assistant.io
    - name: Grafana
      url: http://192.168.2.2:3000/

google:
  client_id: !secret gcalclientid
  client_secret: !secret gcalsecret
  track_new_calendar: True
  
hass_opensprinkler:
  host: opensprinkler.fritz.box
  password: e1d8b87798de200a9feafd9c7d78d2bb

#custom-ui
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/hass-fontawesome-solid.html
    - /local/hass-fontawesome-regular.html
    - /local/hass-fontawesome-brands.html

#weather:
#  - platform: darksky
#    api_key: !darksky_apikey
#    latitude: !secret latitude
#    longitude: !secret longitude
#    units: si
#    mode: hourly


weather:
  - platform: yweather

alarm_control_panel:
  - platform: manual
    name: AllarmeDomotica
    code: 1234
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

#lock:
#  - platform: nuki
#    host: AndroidHomeassistantBridge.fritz.box
#    token: !secret nukitoken

lightingsm:
  tavolosalone:
    sensors: 
      - binary_sensor.motion_sensor_tavolosalone
    sensor_type_duration: True
    entities: 
      - light.tavolo_salone 
      - light.coloritavolosalone
    delay: 180
    overrides:
      - sensor.llim_tavolosalone
      - input_boolean.auto_tavolosalone
    service_data:
      brightness: 100
    night_mode:
      delay: 60
      service_data:
        brightness: 50
      start_time: '00:00:00'                  # required
      end_time: '06:30:00'                    # required

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_key
    allowed_chat_ids: !secret telegram_bot_chat_ids

alexa_media:
  accounts:
    - email: !secret amazonemail
      password: !secret amazonpassword
      url: amazon.it


openuv:
  api_key: !secret openuvkey
  binary_sensors:
    monitored_conditions:
      - uv_protection_window
  sensors:
    monitored_conditions:
      - current_ozone_level
      - current_uv_index
      - current_uv_level
      - max_uv_index
      - safe_exposure_time_type_1
      - safe_exposure_time_type_2
      - safe_exposure_time_type_3
      - safe_exposure_time_type_4
      - safe_exposure_time_type_5
      - safe_exposure_time_type_6

# https://github.com/DavidMStraub/homeassistant-homeconnect/blob/master/custom_components/homeconnect/switch.py
# Bosch Siemens Home Connect

homeconnect:
  client_id: !secret homeconnectclientid
  client_secret: !secret homeconnectclientsecret

scene:
  - name: prova
    entities:
      switch.tavolosalone : on

stream:
alexa:

yeelight:
  devices:
    yeelink-light-strip1-ledlettoale.fritz.box:
      name: SottoLettoAle
    192.168.2.63:
      name: LampadaStudio



device_tracker: !include device_tracker.yaml
group: !include groups.yaml
light: !include lights.yaml
switch: !include switchs.yaml
script: !include scripts.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
intent_script: !include intents.yaml
media_player: !include media_player.yaml
timer: !include timers.yaml
camera: !include cameras.yaml
notify: !include notify.yaml
input_boolean: !include input_boolean.yaml
input_text: !include input_text.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
