// google_assistant:
//  project_id: homeassistantintegration-5af5b
//  client_id: N5xXvdO0gb0r8P2rNdMRsj3jKIu6nwXo6b8Fq7f9n10ueV2wq93rlwmPMBFi60266uzSjHnOAI1i9xne
//  access_token: b65W3oTqolwmCwKfM6Nped1f0zmnK79tw0gj7DSmfm5b5mFh1MXC4uCNnM57afbKXBhI9HW8vDuJV5WA
//  agent_user_id: [a string to identify user]
//  api_key: b65W3oTqolwmCwKfM6Nped1f0zmnK79tw0gj7DSmfm5b5mFh1MXC4uCNnM57afbKXBhI9HW8vDuJV5WA
//  b65W3oTqolwmCwKfM6Nped1f0zmnK79tw0gj7DSmfm5b5mFh1MXC4uCNnM57afbKXBhI9HW8vDuJV5WA
//  exposed_domains:
//    - switch
//    - light
//    - group
// entity_config:
//   switch.kitchen:
//     name: Custom Name for Google Assistant
//     aliases:
//       - bright lights
//        - entry lights
//    light.living_room:
//      expose: false
//      room: living room

