#github backup

homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret Location
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome

    
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  customize_glob: !include customize_glob.yaml

customizer:
  custom_ui: local
zone:
#  - name: !secret School
#    latitude: !secret Schoollatitude
#    longitude: !secret Schoollongitude
#    radius: 100
#    icon: mdi:work

#  - name: !secret WifeWork
#    latitude: !secret WifeWorklatitude
#    longitude: !secret WifeWorklongitude
#    radius: 250
#    icon: mdi:work

#  # This will override the default home zone
  - name: !secret Homelocation
    latitude:  !secret Homelocationlatitude
    longitude:  !secret Homelocationlongitude
    radius: 100
    icon: mdi:account-multiple
#

lovelace:
  mode: yaml

logger:
  default: info
  logs:
     xeoma: debug    
#    homeassistant.components.device_tracker: critical
#    homeassistant.components.camera: critical

# Show links to resources in log and frontend
#introduction:

# Enables configuration UI
config:

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json
  component_urls:
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://reinasserver.fritz.box:3218

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret api_password
#per ritornare a https://thereinas.it levare commenti sotto e port forward 443->8123
#  ssl_certificate: /etc/letsencrypt/live/thereinas.it/fullchain.pem
# ssl_key: /etc/letsencrypt/live/thereinas.it/privkey.pem
# base_url: thereinas.it

  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - harmony
    - bose_soundtouch
    - philips_hue

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
    language: it

# Cloud
cloud:
  alexa:
    filter:
      include_entities:
        - light.tavolo_salone
        - light.cucina
        - light.ingresso
        - light.divano
        - light.idro_gionic
        - light.letto_gionic
        - switch.alberodinatale
        - switch.decorazioninatale
        - group.lucisalone
        - group.luciesterno
    entity_config:
      light.tavolo_salone:
        name: Luce Tavolo Salone
        description: la luce del Tavolo del Salone
      light.cucina:
        name: Luce cucina
        description: la luce della cucina
      light.ingresso:
        name: Luce Ingresso
        description: la luce dell'ingresso
      light.divano:
        name: Luce Divano
        description: la luce del divano
      light.idro_gionic:
        name: Luce Idro
        description: la luce dell'idro
      light.letto_gionic:
        name: Luce Letto GioNic
        description: la luce del letto Gio Nic
      switch.alberodinatale:
        name: albero di natale
        description: albero di natale
      switch.decorazioninatale:
        name: decorazioni natale
        description: decorazioni di natale
      group.lucisalone:
        name: luci salone
        description: luci salone
      group.luciesterno:
        name: luci esterno
        description: luci esterno

intent_script:
  RunScriptIntent:
    action:
      service: script.turn_on
      data_template:
        entity_id: script.{{ Script | replace(" ", "_") }}
    speech:
      type: plain
      text: Va bene

#  amzn1.ask.skill.31d2ff24-5617-448b-8cdc-1c666520a0b2:
#    action:
#      service: script.turn_on
#      entity_id: script.accendi_sky
#    speech:
#      type: plain
#      text: OK

mqtt:
  broker: ReinasServer.fritz.box
  port: 1883
  client_id: hass
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: xeoma
    host: http://ReinasServer.fritz.box:10090
    username: !secret XeomaUser
    password: !secret XeomaPassword
    new_version: true
#    cameras:
#      - image_name: salone
#        name: salone
#      - image_name: cucina
#        name: cucina
#      - image_name: letto
#        name: letto

  - platform: ffmpeg
    name: Letto_f
    input: -rtsp_transport tcp -i rtsp://dafangletto.fritz.box:8554/unicast
  - platform: ffmpeg
    name: Ingresso_f
    input: -rtsp_transport tcp -i rtsp://dafangsalone.fritz.box:8554/unicast
  - platform: ffmpeg
    name: Cucina_f
    input: -rtsp_transport tcp -i rtsp://dafangcucina.fritz.box:8554/unicast

  - platform: mqtt
    topic: ReinasHome/TelecameraCucina
  - platform: mqtt
    topic: ReinasHome/TelecameraIngresso
  - platform: mqtt
    topic: ReinasHome/TelecameraLetto

#  - platform: arlo
#    ffmpeg_arguments: '-pred 1 -q:v 2'


xiaomi_aqara:
  discovery_retry: 15
  gateways:
    - mac: 34:CE:00:82:96:03
      key: !secret AquaraKey0
      host: XiaomiGateway0.fritz.box
    - mac: 7C:49:EB:19:03:79
      key: !secret AquaraKey1
      host: XiaomiGateway1.fritz.box

remote:
  - platform: harmony
    name: ReinasHarmony
    host: HarmonyHub.fritz.box

bmw_connected_drive:
  name:
    username: !secret BMWUSER
    password: !secret BMWPWD
    region: "rest_of_world"

#climate:
#  - platform: honeywell
#    username: !secret EvoHomeUser
#    password: !secret EvoHomePassword
#    scan_interval: 600

evohome:
  username: !secret EvoHomeUser
  password: !secret EvoHomePassword

device_tracker:
  - platform: unifi
    host: ReinasServer.fritz.box
    username: !secret UnifiUser
    password: !secret UnifiPassword
    verify_ssl: false

ifttt:
  key: !secret IFTTKEY

recorder:
  db_url: mysql://hass:toorhass@localhost/hassdb

influxdb:
  host: Reinasserver.fritz.box
  port: 8086
  database: hass
  username: !secret influxuser
  password: !secret influxdbpassword


vacuum:
  - platform: xiaomi_miio
    host: rockrobo.fritz.box
    token: 4f73323044716757674f6b5a57534a61

zwave:
#  usb_path: /dev/ttyACM0
  usb_path: /dev/zwave

#/etc/udev/rules.d/99-usb-serial.rules 
#SUBSYSTEM=="tty", ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200", SYMLINK+="zwave"


#google_assistant:
#  project_id: homeassistantintegration-5af5b
#  client_id: !secret google_client_id
#  access_token:  !secret google_access_token
#  api_key: !secret google_api_key
#  exposed_domains:
#    - switch
#    - light
#    - group
#    - script

weblink:
  entities:
    - name: Router
      url: http://192.168.2.1/
      icon: mdi:router-wireless
    - name: Home Assistant
      url: https://www.home-assistant.io
    - name: Grafana
      url: http://192.168.2.2:3000/

#telegram_bot:
#  - platform: polling
#    api_key: !secret telegram_apikey
#    allowed_chat_ids:
#      - CHAT_ID_1
#      - CHAT_ID_2
#      - CHAT_ID_3

#      MediaSalone:
#        friendly_name: 'Reinas Media'
#        value_template: "{{ states.sun.sun.attributes.next_rising }}"
#        value_template: "{{ states.remote.reinasharmony.attributes.current_activity }}"

input_number:
  wakeup_hour:
    name: Hour
    icon: mdi:clock-in
    initial: 6
    min: 0
    max: 23
    step: 1
  wakeup_minutes:
    name: Minutes
    icon: mdi:clock-in
    initial: 30
    min: 0
    max: 55
    step: 5
  wakeup_duration:
    name: Light fadein
    icon: mdi:clock-in
    initial: 10
    min: 5
    max: 60
    step: 5
  internet_cut_time:
    name: 'Disconnection time (min)'
    initial: 120
    min: 2
    max: 240
    step: 1
  internet_cut_hour:
    name: Hour
    icon: mdi:timer
    initial: 1
    min: 0
    max: 23
    step: 1
  internet_cut_minutes:
    name: Minutes
    icon: mdi:timer
    initial: 05
    min: 0
    max: 55
    step: 5

input_text:
  scene_temp_var:
    initial: 'off:1'

input_boolean:
  daily_vacuum_first_run:
    name: Daily Vacuum First Run
    initial: 'off'
  disable_daily_vacuum:
    name: Disable Daily Vacuum Automation
    initial: 'off'
  disable_dustbin_notification:
    name: Disable Dustbin Notification
    initial: 'off'

  wakeup:
    name: 'Enable wakeup light'
    icon: mdi:power
    initial: off
  wakeup_weekends:
    name: 'Wakeup weekends'
    icon: mdi:power
    initial: off

input_select:
  vacuum_room:
    name: Choose a room to clean
    options:
      - Select Input
      - salone 
      - ingresso 
      - salone solo divano
      - salone solo tavolo
      - cucina
      - stanza da letto
      - stanza esclusa cabina e bagno
      - bagno
      - cabina

google:
  client_id: !secret gcalclientid
  client_secret: !secret gcalsecret

hass_opensprinkler:
  host: opensprinkler.fritz.box
  password: e1d8b87798de200a9feafd9c7d78d2bb

#custom-ui
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/hass-fontawesome-solid.html
    - /local/hass-fontawesome-regular.html
    - /local/hass-fontawesome-brands.html

#weather:
#  - platform: darksky
#    api_key: !darksky_apikey
#    latitude: !secret latitude
#    longitude: !secret longitude
#    units: si
#    mode: hourly
weather:
  - platform: yweather

#- platform: mijnafvalwijzer
#  postcode: !secret afvalwijzer_postcode
#  huisnummer: !secret afvalwijzer_huisnummer
#  toevoeging: !secret afvalwijzer_toevoeging

alarm_control_panel:
  - platform: manual
    name: AllarmeDomotica
#    code: 1234
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

#alexa:  


group: !include groups.yaml
light: !include lights.yaml
switch: !include switchs.yaml
script: !include scripts.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
notify: !include notify.yaml
intent_script: !include intents.yaml
media_player: !include media_player.yaml
timer: !include timers.yaml
