#github backup
homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret Location
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  customize_glob: !include customize_glob.yaml
customizer:
  custom_ui: local
zone:
#  - name: !secret School
#    latitude: !secret Schoollatitude
#    longitude: !secret Schoollongitude
#    radius: 100
#    icon: mdi:work

#  - name: !secret WifeWork
#    latitude: !secret WifeWorklatitude
#    longitude: !secret WifeWorklongitude
#    radius: 250
#    icon: mdi:work

#  # This will override the default home zone
  - name: !secret Homelocation
    latitude:  !secret Homelocationlatitude
    longitude:  !secret Homelocationlongitude
    radius: 100
    icon: mdi:account-multiple
#


# Show links to resources in log and frontend
#introduction:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret api_password
#per ritornare a https://thereinas.it levare commenti sotto e port forward 443->8123
#  ssl_certificate: /etc/letsencrypt/live/thereinas.it/fullchain.pem
# ssl_key: /etc/letsencrypt/live/thereinas.it/privkey.pem
# base_url: thereinas.it

  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - harmony
    - bose_soundtouch
    - philips_hue

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
#tts:
#  - platform: google
#    language: it
# Cloud
cloud:


mqtt:
  broker: ReinasServer.thereinas.it
  port: 1883
  client_id: hass
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant

camera:
  - platform: xeoma
    host: http://ReinasServer.Thereinas.it:10090
    username: !secret XeomaUser
    password: !secret XeomaPassword
    new_version: true
    cameras:
      - image_name: Ingresso
        name: Ingresso
      - image_name: Cucina
        name: Cucina
      - image_name: Letto 
        name: Letto

  - platform: ffmpeg
    name: Letto_f
    input: -rtsp_transport tcp -i rtsp://dafangletto.thereinas.it:8554/unicast
  - platform: ffmpeg
    name: Ingresso_f
    input: -rtsp_transport tcp -i rtsp://dafangingresso.thereinas.it:8554/unicast
  - platform: ffmpeg
    name: Cucina_f
    input: -rtsp_transport tcp -i rtsp://dafangcucina.thereinas.it:8554/unicast

  - platform: mqtt
    topic: ReinasHome/TelecameraCucina
  - platform: mqtt
    topic: ReinasHome/TelecameraIngresso
  - platform: mqtt
    topic: ReinasHome/TelecameraLetto

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: 34:CE:00:82:96:03
      key: !secret AquaraKey

remote:
  - platform: harmony
    name: ReinasHarmony
    host: HarmonyHub.thereinas.it

bmw_connected_drive:
  name:
    username: !secret BMWUSER
    password: !secret BMWPWD
    region: "rest_of_world"

climate:
  - platform: honeywell
    username: !secret EvoHomeUser
    password: !secret EvoHomePassword
    scan_interval: 600

evohome:
  username: !secret EvoHomeUser
  password: !secret EvoHomePassword

device_tracker:
  - platform: unifi
    host: ReinasServer.thereinas.it
    username: !secret UnifiUser
    password: !secret UnifiPassword
    verify_ssl: false

ifttt:
  key: !secret IFTTKEY

recorder:
  db_url: mysql://hass:hasstoor@localhost/hass

influxdb:
  host: Reinasserver.thereinas.it
  port: 8086
  database: hass
  username: hass
  password: !secret influxdbpassword


vacuum:
  - platform: xiaomi_miio
    host: rockrobo.thereinas.it
    token: 7a3864656c797245775a4f514f356850

zwave:
#  usb_path: /dev/ttyACM0
  usb_path: /dev/zwave

#/etc/udev/rules.d/99-usb-serial.rules 
#SUBSYSTEM=="tty", ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200", SYMLINK+="zwave"


media_player:
  - platform: soundtouch
    host: SoundTouch.TheReinas.it
    port: 8090
    name: SoundtouchReinas

  - platform: alexa
    email: !secret amazonemail
    password: !secret amazonpassword
    url: amazon.it

#google_assistant:
#  project_id: homeassistantintegration-5af5b
#  client_id: !secret google_client_id
#  access_token:  !secret google_access_token
#  api_key: !secret google_api_key
#  exposed_domains:
#    - switch
#    - light
#    - group
#    - script

weblink:
  entities:
    - name: Router
      url: http://192.168.2.1/
      icon: mdi:router-wireless
    - name: Home Assistant
      url: https://www.home-assistant.io
    - name: Grafana
      url: http://192.168.2.2:3000/

#hue:
#  bridges:
#    - host: 192.168.2.10
#      filename: phue.conf
#      allow_unreachable: true
#     allow_hue_groups: false

#telegram_bot:
#  - platform: polling
#    api_key: !secret telegram_apikey
#    allowed_chat_ids:
#      - CHAT_ID_1
#      - CHAT_ID_2
#      - CHAT_ID_3

#input_number:
#  n1:
#    name: Sensore Attivo da Ore
#    initial: 8
#    min: 0
#    max: 23
#    step: 1
#    mode: box
#  n2:
#    name: Sensore Attivo da min
#    initial: 0
#    min: 0
#    max: 45
#    step: 15
#    mode: box
#  n3:
#    name: Sensore Attivo alle Ore
#    initial: 8
#    min: 0
#    max: 23
#    step: 1
#    mode: box
#  n4:
#    name: Sensore Attivo a min
#    initial: 0
#    min: 0
#    max: 45
#    step: 15
#    mode: box
#  n5:
#    name: Timeout Spegnimento Luce
#    initial: 5
#    min: 0
#    max: 20
#    step: 1
#    mode: box

#sensor:
#  - platform: template
#    sensors:
#      solar_angle:
#        friendly_name: "Sun angle"
#        unit_of_measurement: 'degrees'
#        value_template: "{{ states.sun.sun.attributes.elevation }}"

#      sunrise:
#        friendly_name: 'Sunrise'
#        value_template: "{{ states.sun.sun.attributes.next_rising }}"

#      MediaSalone:
#        friendly_name: 'Reinas Media'
#        value_template: "{{ states.sun.sun.attributes.next_rising }}"
#        value_template: "{{ states.remote.reinasharmony.attributes.current_activity }}"

#      Consumo_infrastruttura:
#        friendly_name: "Consumo Infrastruttura"
#        unit_of_measurement: 'W'
#        value_template: "{{ states.switch.infrastruttura.attributes.load_power }}"

#      ConsumoInfrastruttura:
#        unit_of_measurement: 'W'
#        value_template: "{{ states.switch.infrastruttura.attributes.load_power }}"

#      ConsumoEntertainment:
#        friendly_name: "Consumo Entertainment"
#        unit_of_measurement: 'W'
#        value_template: "{{ states.switch.family_entertainment.attributes.load_power }}"

input_number:
  wakeup_hour:
    name: Hour
    icon: mdi:clock-in
    initial: 6
    min: 0
    max: 23
    step: 1
  wakeup_minutes:
    name: Minutes
    icon: mdi:clock-in
    initial: 30
    min: 0
    max: 55
    step: 5
  wakeup_duration:
    name: Light fadein
    icon: mdi:clock-in
    initial: 10
    min: 5
    max: 60
    step: 5

input_boolean:
  wakeup:
    name: 'Enable wakeup light'
    icon: mdi:power
    initial: off
  wakeup_weekends:
    name: 'Wakeup weekends'
    icon: mdi:power
    initial: off

input_text:
  scene_temp_var:
    initial: 'off:1'


opensprinkler:
  host: 192.168.2.6
  port: 80
  password: e1d8b87798de200a9feafd9c7d78d2bb

#custom-ui
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/hass-fontawesome-solid.html
    - /local/hass-fontawesome-regular.html
    - /local/hass-fontawesome-brands.html


group: !include groups.yaml
light: !include lights.yaml
switch: !include switchs.yaml
script: !include scripts.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
