title: Casa
views:

########################################################################################
# Luce
########################################################################################

  - title: Luce
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: entity-button
            entity: light.lucisalone
            tap_action: toggle
################
# Salone
################
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: light.cespuglioingressosalone
                tap_action: toggle
              - type: entity-button
                entity: light.cespugliodivanosalone
                tap_action: toggle
              - type: entity-button
                entity: light.tavolosalone_2
                tap_action: toggle
################
# Cucina
################
          - type: entity-button
            entity: light.lucisalone
            tap_action: toggle
          - type: horizontal-stack
            cards:
             - type: entity-button
               entity: light.lucecucina
               tap_action: toggle
             - type: entity-button
               entity: light.lucecucina
               tap_action: toggle
             - type: entity-button
               entity: light.lucecucina
               tap_action: toggle
################
# GioNic
################
          - type: entity-button
            entity: light.lucigionic
            tap_action: toggle
          - type: horizontal-stack
            cards:
             - type: entity-button
               entity: light.gionic
               tap_action: toggle
             - type: entity-button
               entity: light.lettogionic_2
               tap_action: toggle
             - type: entity-button
               entity: light.plug_lampadasale
               tap_action: toggle
             - type: entity-button
               entity: light.idromassaggio
               tap_action: toggle
             - type: entity-button
               entity: light.esternocabina
               tap_action: toggle
################
# Esterno Portico
################
          - type: entity-button
            entity: light.luciesterno
            tap_action: toggle
          - type: horizontal-stack
            cards:
             - type: entity-button
               entity: light.esternoale
               tap_action: toggle
             - type: entity-button
               entity: light.esternocancelletto
               tap_action: toggle
             - type: entity-button
               entity: light.esternocucina
               tap_action: toggle
             - type: entity-button
               entity: light.esternosalone
               tap_action: toggle
################
# Esterno Giardino
################
          - type: entity-button
            entity: light.lucigiardino
            tap_action: toggle
          - type: horizontal-stack
            cards:
             - type: entity-button
               entity: light.giardinovicino
               tap_action: toggle
             - type: entity-button
               entity: light.giardinolontano
               tap_action: toggle

########################################################################################
# Energia
########################################################################################

  - title: Energia
    panel: true
    cards:
      - type: horizontal-stack
        cards:
         - type: gauge
           title: Scambio
           unit_of_measurement: W
           min: -3000
           max: 3000
           severity:
             green: -3000
             yellow: 0
             red: 1500
           entity: sensor.scambio_casa
         - type: gauge
           title: Consumo
           unit_of_measurement: W
           min: 0
           max: 6000
           severity:
             green: 0
             yellow: 1500
             red: 3000
           entity: sensor.consumo_casa
         - type: gauge
           title: Produzione
           unit_of_measurement: W
           min: 0
           max: 3000
           entity: sensor.produzione_casa

########################################################################################
# Confort
########################################################################################

  - title: Confort
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: weather-forecast
                entity: weather.yweather
          - type: horizontal-stack
            cards:
                - type: thermostat
                  entity: climate.salone
                - type: thermostat
                  entity: climate.gio_e_nic
                - type: thermostat
                  entity: climate.bagno_salone
          - type: horizontal-stack
            cards:
                - type: thermostat
                  entity: climate.bea
                - type: thermostat
                  entity: climate.ale
                - type: thermostat
                  entity: climate.bagno_su
          - type: horizontal-stack
            cards:
                - type: thermostat
                  entity: climate.salone_taverna
                - type: thermostat
                  entity: climate.bagno_taverna
                - type: thermostat
                  entity: climate.letto_taverna
                - type: thermostat
                  entity: climate.salone_taverna
